export const FATCH_MEDICINE = "FATCH_MEDICINE";
export const ERROR_MEDICINE = "ERROR_MEDICINE";
export const LODING_MEDICINE = "LODING_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const EDIT_MEDICINE ="EDIT_MEDICINE";

export const FETCH_DOCTORS = "FETCH_DOCTORS";
export const ERROR_DOCTORS = "ERROR_DOCTORS";
export const LOAD_DOCTORS = "LOAD_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";
export const EDIT_DOCTORS = "EDIT_DOCTORS";
export const DOCTORS_ADD = "DOCTORS_ADD";

export const FATCH_PATIENT = "FATCH_PATIENT";
export const RETRIEVED_PATIENTS = "RETRIEVED_PATIENTS";
export const ADD_PATIENTS = "ADD_PATIENTS";
export const ADDED_PATIENTS = "ADDED_PATIENTS";

export const FATCH_USER = "FATCH_USER";
export const RETRIEVED_USER = "RETRIEVED_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETED_USER = "DELETED_USER";