export const FATCH_MEDICINE = "FATCH_MEDICINE";
export const ERROR_MEDICINE = "ERROR_MEDICINE";
export const LODING_MEDICINE = "LODING_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const EDIT_MEDICINE ="EDIT_MEDICINE";